# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.IntegerField(unique=True, verbose_name='Prontuário')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino')], default='Masculino', max_length=10)),
                ('datanascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.TextField(blank=True, null=True)),
                ('turma', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'verbose_name': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'verbose_name': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Locais',
                'verbose_name': 'Local',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('datahora', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Data notificação')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('titulo', models.CharField(max_length=45, verbose_name='Título')),
                ('id_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.Local', verbose_name='Local')),
            ],
            options={
                'verbose_name_plural': 'Notificações',
                'verbose_name': 'Notificação',
            },
        ),
        migrations.CreateModel(
            name='Remetente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Remetentes',
                'verbose_name': 'Remetente',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.IntegerField(unique=True, verbose_name='Prontuário')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino')], default='Masculino', max_length=10)),
                ('datanascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.TextField(blank=True, null=True)),
                ('funcao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Função')),
            ],
            options={
                'verbose_name_plural': 'Servidores',
                'verbose_name': 'Servidor',
            },
        ),
        migrations.CreateModel(
            name='Tipoformacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Tipos Formações',
                'verbose_name': 'Tipo Formação',
            },
        ),
        migrations.CreateModel(
            name='Tiponotificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Título')),
                ('cor', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos Notificações',
                'verbose_name': 'Tipo Notificação',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('remetente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notificacao.Remetente')),
                ('ativo', models.TextField(blank=True, null=True)),
                ('disciplinas', models.ManyToManyField(to='notificacao.Disciplina')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'verbose_name': 'Curso',
            },
            bases=('notificacao.remetente',),
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('remetente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notificacao.Remetente')),
                ('datafundacao', models.DateField(blank=True, null=True, verbose_name='Data de fundação')),
            ],
            options={
                'verbose_name_plural': 'Institutos',
                'verbose_name': 'Instituto',
            },
            bases=('notificacao.remetente',),
        ),
        migrations.CreateModel(
            name='Oferecimento',
            fields=[
                ('remetente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notificacao.Remetente')),
                ('ano', models.DateField(default=datetime.date.today)),
                ('semestre', models.IntegerField(choices=[(1, 'Primeiro'), (2, 'Segundo')], default=1)),
                ('alunos', models.ManyToManyField(to='notificacao.Aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Disciplina')),
            ],
            options={
                'verbose_name_plural': 'Oferecimentos',
                'verbose_name': 'Oferecimento',
            },
            bases=('notificacao.remetente',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('servidor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notificacao.Servidor')),
                ('formacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Área')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Tipoformacao', verbose_name='Tipo formação')),
            ],
            options={
                'verbose_name_plural': 'Professores',
                'verbose_name': 'Professor',
            },
            bases=('notificacao.servidor',),
        ),
        migrations.CreateModel(
            name='Salaalunos',
            fields=[
                ('remetente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notificacao.Remetente')),
                ('alunos', models.ManyToManyField(to='notificacao.Aluno')),
                ('id_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.Curso')),
            ],
            options={
                'verbose_name_plural': 'Salas Alunos',
                'verbose_name': 'Sala Alunos',
            },
            bases=('notificacao.remetente',),
        ),
        migrations.CreateModel(
            name='Salaprofessores',
            fields=[
                ('remetente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notificacao.Remetente')),
                ('id_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.Curso')),
                ('professores', models.ManyToManyField(to='notificacao.Professor')),
            ],
            options={
                'verbose_name_plural': 'Salas Professores',
                'verbose_name': 'Sala Professores',
            },
            bases=('notificacao.remetente',),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Tiponotificacao', verbose_name='Tipo notificação'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Servidor'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='remetente',
            field=models.ManyToManyField(to='notificacao.Remetente'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='id_instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Instituto'),
        ),
        migrations.AddField(
            model_name='oferecimento',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Professor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Instituto'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Instituto'),
        ),
    ]
