# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferecimento',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='oferecimento',
            name='semestre',
        ),
        migrations.AddField(
            model_name='oferecimento',
            name='dataInicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='dd/mm/yyyy', verbose_name='Data Início'),
        ),
        migrations.AddField(
            model_name='oferecimento',
            name='qtdAulas',
            field=models.IntegerField(choices=[(1, 10), (2, 20)], default=2, verbose_name='Quantidade Aulas'),
        ),
    ]
