# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='id_instituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.Instituto'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.CharField(default=1, max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='formacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='id_instituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.Instituto'),
        ),
    ]
