# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remetente',
            name='tipo',
            field=models.CharField(default='Tipo', max_length=50, verbose_name='Tipo'),
        ),
    ]
