# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='professor',
            name='tipo_formacao',
            field=models.TextField(choices=[('Graduação', 'Graduação'), ('Pós Graduação', 'Pós Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós Doutorado', 'Pós Doutorado'), ('Livre Docência', 'Livre Docência')], default='Graduação', verbose_name='Tipo formação'),
        ),
        migrations.DeleteModel(
            name='TipoFormacao',
        ),
    ]
