# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_auto_20170509_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferecimento',
            name='qtd',
            field=models.IntegerField(default=1, verbose_name='Quantidade de aulas'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Admin sistema'),
        ),
    ]
