# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_auto_20161206_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='tipo_formacao',
            field=models.CharField(choices=[('Técnico', 'Técnico'), ('Graduação', 'Graduação'), ('Pós Graduação', 'Pós Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós Doutorado', 'Pós Doutorado'), ('Livre Docência', 'Livre Docência')], default='Graduação', max_length=15, verbose_name='Tipo formação'),
        ),
    ]
