# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_auto_20160905_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='tipo_formacao',
            field=models.CharField(choices=[('Graduação', 'Graduação'), ('Pós Graduação', 'Pós Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós Doutorado', 'Pós Doutorado'), ('Livre Docência', 'Livre Docência')], default='Graduação', max_length=15, verbose_name='Tipo formação'),
        ),
    ]
