# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_remetente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='datafundacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Fundação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='datahora',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Acontecimento'),
        ),
    ]
