# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_auto_20160810_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='formacao',
            field=models.CharField(default=1, max_length=20, verbose_name='Área'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='id_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.TipoFormacao', verbose_name='Tipo formação'),
        ),
    ]
