# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0003_auto_20160905_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='id_instituto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.Instituto'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='id_instituto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacao.Instituto'),
        ),
    ]
