# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 21:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0003_auto_20170705_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 7 characters.', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('([0-9]{7})(?!\\w|\\.)$', 'Enter a valid username. This value may contain only letters, numbers characters.')], verbose_name='Prontuário'),
        ),
    ]
