# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 22:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notificacao', '0003_auto_20171016_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferecimento',
            name='id_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='notificacao.Professor'),
        ),
    ]
