# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notificacao', '0004_auto_20171024_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
