# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0004_auto_20160810_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='ativo',
        ),
        migrations.AddField(
            model_name='remetente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
