# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notificacao', '0005_auto_20171025_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
