# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0005_auto_20160823_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remetente',
            old_name='ativo',
            new_name='is_active',
        ),
    ]
