# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notificacao', '0006_auto_20171025_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='formacao',
            field=models.CharField(max_length=30, verbose_name='Área'),
        ),
    ]
