# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 21:19
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0006_auto_20160824_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiponotificacao',
            name='cor',
            field=colorfield.fields.ColorField(max_length=10),
        ),
    ]
