# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0008_auto_20160824_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
