# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificacao', '0009_disciplina_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='remetente',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
