# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificacao', '0010_remetente_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='content_type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servidor',
            name='content_type',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
