# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0013_auto_20160831_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='content_type',
        ),
    ]
