# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0014_auto_20160831_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='datanascimento',
            field=models.DateField(default=django.utils.timezone.now, help_text='dd/mm/yyyy', verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='datafundacao',
            field=models.DateField(blank=True, help_text='dd/mm/yyyy', null=True, verbose_name='Data de fundação'),
        ),
        migrations.AlterField(
            model_name='oferecimento',
            name='ano',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2016, max_length=4, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='datanascimento',
            field=models.DateField(default=django.utils.timezone.now, help_text='dd/mm/yyyy', verbose_name='Data de nascimento'),
        ),
    ]
